corsarotagger/configparser.c
corsarotagger/corsarotagger.h
corsarotagger/tagger_thread.c
libcorsaro/libcorsaro_tagging.c

Also removes a whole bunch of unnecessary code relating to tagger output hashbins, which are no longer used since the switch to multicast output.

Fix byte ordering of filtbits in the tagger

---

libcorsaro/plugins/report/merging_thread.c

Rather than send the ICMP typecode value to the database smooshed into one value, split it out into type and code separately.

Tweak ICMP typecode metric string

---

corsarotrace/corsarotrace.c
libcorsaro/plugins/report/processing_thread.c

* Fix race condition that sometime would cause corsarotrace to hang when on exit (when using the report plugin).
* Fix bug where unique destination IP counts for some report metrics were always zero.
* Fix misleading loss report phrasing in corsarotrace.

Fixes for issues found after deploying the multicast tagger

---

corsarotrace/configparser.c
corsarotrace/corsarotrace.c
corsarotrace/corsarotrace.h

The "stats" file works the same way it does for corsarotagger.
For each interval, each thread writes its stats for that interval
to a uniquely named stats file. The stats are overwritten at each
interval, so if they aren't scraped before the next interval then
they will be lost (this copies the tagger behaviour).
The stats that corsarotrace will write are:
* interval timestamp
* number of packets received by that thread
* number of packets detected as dropped by that thread
* number of instances of packet loss detected by that thread
(a loss instance may result in multiple packets being lost)
* number of packets seen that should have been seen during an
earlier interval (indicates packet reordering is happening).

corsarotrace: add option to write stats to a file

---

libcorsaro/libcorsaro_tagging.c
libcorsaro/plugins/report/corsaro_report.c
libcorsaro/plugins/report/iptracker_thread.c
libcorsaro/plugins/report/merging_thread.c
libcorsaro/plugins/report/report_internal.h

The main goal here has been to reduce the number of lookups in the "metric map" that the IP tracker threads use to accumulate packet counts and unique IPs + ASNs for each metric that we care about.
There are two key changes here:
1. metrics where the range of possible values is finite and densely populated are now tracked in conventional arrays rather than a Judy array. This covers the metrics for IP protocols, TCP ports, the individual filter criteria and the "combined" metric.
2. Netacuity geolocation metrics are now only tracked for the most-specific location tag for each observed packet. This will be county for US locations and region for most other countries. The corresponding less specific tags (e.g. continent, country, region for US locations) are instead noted alongside the …

More report plugin performance enhancements

---

libcorsaro/libcorsaro_avro.c
libcorsaro/libcorsaro_avro.h

This is helpful when trying to minimize latency between an output file being finished and some external process doing something with it.

Create .done files when closing avro output

---

corsarotrace/configparser.c
corsarotrace/corsarotrace.c
docs/corsarotrace-README.md
libcorsaro/plugins/corsaro_flowtuple.c

This allows the number of processing threads to be explicitly configured when using corsarotrace in "offline" mode. It also adds a sanity check to the flowtuple plugin in case the number of merge threads is less than the number of processing threads.

Re-add `threads` option for corsarotrace

---

corsarowdcap/corsarowdcap.c

Note: you'll also want to upgrade to libtrace 4.0.14 as well to get the fixes found in https://github.com/LibtraceTeam/libtrace/pull/133/files.

corsarowdcap: fix issues caused when processing threads do not see a packet for a whole interval

---

docs/corsarotrace-README.md
exampleconfigs/reportconfig.yaml
libcorsaro/plugins/report/corsaro_report.c
libcorsaro/plugins/report/iptracker_thread.c
libcorsaro/plugins/report/merging_thread.c
libcorsaro/plugins/report/processing_thread.c
libcorsaro/plugins/report/report_internal.h

Rather than naively producing 65536 time series for each port metric, we now have the ability to limit the number of series that we produce to specific ports that are "interesting".
This will both decrease our general workload when running the report plugin, as well as lowering our daily storage requirements.

Report plugin: add ability to limit TCP and UDP port series to specific port numbers or ranges

---

docs/corsarotrace-README.md
exampleconfigs/reportconfig.yaml
libcorsaro/libcorsaro_tagging.c
libcorsaro/plugins/report/corsaro_report.c
libcorsaro/plugins/report/merging_thread.c
libcorsaro/plugins/report/processing_thread.c
libcorsaro/plugins/report/report_internal.h

For some levels of filtering, we don't really need to continuously track statistics for every single region or county.
This option allows for the region / county / polygon levels of geo-tagging to be ignored by the report plugin if so desired.
Also includes a fix for a bad series labeling bug that I found while testing this new feature -- the bug occurs when corsarotrace is unable to find a suitable IPmeta label for a metric ID for whatever reason. Now such metrics are quietly ignored.

Add option to limit geo-tagged time series to continent and country only

---

libcorsaro/plugins/report/iptracker_thread.c

Only try to add the ASN to the ASN map **if** this source IP address is new -- if we already have the address in the IP map,
then we should also already have the corresponding ASN in the ASN map...

report: try to reduce processing workload for unique ASN counts

---

docs/corsarotrace-README.md
exampleconfigs/reportconfig.yaml
libcorsaro/plugins/report/corsaro_report.c
libcorsaro/plugins/report/iptracker_thread.c
libcorsaro/plugins/report/processing_thread.c
libcorsaro/plugins/report/report_internal.h

The main purpose of these options is to try and offer more efficient methods of counting that trade-off CPU usage against the precision of the numbers reported for the unique IP counts.
The numbers instead become an approximation, but should still follow any major changes or spikes that we would otherwise see with the full unique IP counts.
Two methods have been added:
* prefix aggregation, which simply counts unique /N prefixes where N is configurable -- performance gains are modest in terms of CPU, good in terms of memory, relative precision loss is low
* sampling, which only increments the counter if the observed address is a particular one for a given /N prefix. The sampled address changes each interval to try and avoid side-effects due to particular addresses being more or less …

report: add config options to count aggregated or sampled IPs 

---

libcorsaro/libcorsaro_filtering.c
libcorsaro/libcorsaro_filtering.h

All TTL 200+ packets will continue to be considered as erratic (i.e. non-erratic counts will be unchanged), but non-spoofed traffic counts should now increase considerably.

Only count TTL 200+ packets as nonspoofed if they are NOT masscan

---

configure.ac
corsarotagger/corsarotagger.c
corsarotagger/corsarotagger.h
debian/changelog
libcorsaro/libcorsaro_tagging.c

This change aims to resolve packet loss issues seen in production whenever an IPmeta reload is triggered on a tagger.

corsarotagger: do not free outdated IPmeta info in tagging threads

---

libcorsaro/libcorsaro_avro.c
libcorsaro/libcorsaro_avro.h

This is going to be required for the proposed flowtuple4 format, which aims to reduce the storage footprint of flowtuple Avro files.

corsaro_avro: add encoding support for an array of integers

---

corsaroftmerge/corsaroftmerge.c
libcorsaro/Makefile.am
libcorsaro/libcorsaro_flowtuple.c
libcorsaro/libcorsaro_flowtuple.h
libcorsaro/plugins/Makefile.am
libcorsaro/plugins/corsaro_flowtuple.c
libcorsaro/plugins/corsaro_flowtuple.h

Previously, we were installing a header that nobody could actually
use as it pulled in other internal headers. However, it does
make sense for the flowtuple "data" to be defined as a structure
that is available in the public API (especially along with our
avro encode and decode functions).
Key changes:
* added libcorsaro_flowtuple.h file which will be installed in
$(prefix)/include -- this contains a flowtuple_data structure
definiton and prototypes for the avro encode/decode functions.
* updated flowtuple structure definition in
plugins/corsaro_flowtuple.h to have a flowtuple_data member,
as well as all the internal members (priority queue stuff,
sorting keys etc).
* plugins/*.h are now no longer installed by corsaro. Any code
that was using these headers (and therefore probably didn't …

Separate public flowtuple structure from internal equivalent

---

libcorsaro/libcorsaro_plugin.c
libcorsaro/libcorsaro_plugin.h
libcorsaro/plugins/corsaro_dos.c

* Stop writing individual flows from attack vectors to an avro file.
* Add new fields to attack vectors: first_attack_port and first_target_port
* Fix bug where corsaro tags were included in the `initial_packet` field
* Fix incorrect ICMP mismatch counting when the packet was an Echo Reply
* Add maxmind geo-tags to attack vectors
* Stop tracking individual packet timestamps for attack vectors, as this data was unused and also CPU-intensive to maintain
* Processing threads now reset their attack IP maps at each interval boundary
* Attack IP maps now only track unique /16s observed, rather than all unique individual addresses (which can result in very large maps for long-running attacks)
* Use packet tags for faster backscatter recognition (where available).

Update rsdos plugin to reduce resource requirements

---

Makefile.am
configure.ac

Not all corsaro use-cases require the tagger and the tagger adds additional dependencies (such as libndagserver).
Rather than force the installation of the extra dependencies for an application that won't need them, let's give users the option of disabling the tagger build outright and only check for those dependencies if it is enabled.
Also libndagserver doesn't build nicely on our FreeBSD 10.1 hosts, so I needed a way to bypass this dependency anyway ;)

Add configure option to disable building the corsarotagger

---

configure.ac
debian/changelog
debian/control
libcorsaro/libcorsaro_libtimeseries.c

Also bump version to 3.4.1
* By default, time series output will use the new 'tskkey' partitioning scheme added in libtimeseries 1.0.3
* Update debian control to require libtimeseries-dev >= 1.0.3

Report change default partitioning

---

docker/rsdos2-ascii/Dockerfile

This should prevent any further crashes due to libpacketdump
failing to safely decode a bogus initial packet -- we don't
need to decode the packet to generate our CSVs, so just
disable the dumping and remove the "warning" about libpacketdump
not being available.

rsdos2ascii: disable dumping initial packet using libpacketdump
